/**
 * Animated loading state during walk generation.
 * Shows a pulsing animation and status text while the AI generates a walk.
 */
import React, { useEffect, useRef } from 'react';
import { View, Text, Animated, StyleSheet } from 'react-native';

export interface GenerationLoadingStateProps {
  /** Optional status message to display */
  message?: string;
}

/**
 * GenerationLoadingState displays an animated pulsing indicator
 * while the walk is being generated by the AI.
 */
export default function GenerationLoadingState({
  message = 'Generating your walk…',
}: GenerationLoadingStateProps): JSX.Element {
  const pulseAnim = useRef(new Animated.Value(0.4)).current;

  useEffect(() => {
    const animation = Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, {
          toValue: 1,
          duration: 800,
          useNativeDriver: true,
        }),
        Animated.timing(pulseAnim, {
          toValue: 0.4,
          duration: 800,
          useNativeDriver: true,
        }),
      ]),
    );
    animation.start();
    return () => animation.stop();
  }, [pulseAnim]);

  return (
    <View style={styles.container} accessibilityRole="progressbar" accessibilityLabel={message}>
      <Animated.View style={[styles.pulse, { opacity: pulseAnim }]} />
      <Text style={styles.message}>{message}</Text>
      <Text style={styles.hint}>This usually takes a few seconds</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    gap: 16,
  },
  pulse: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#C3B1FF',
  },
  message: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  hint: {
    fontSize: 13,
    color: '#484848',
  },
});
